/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package adthena

import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

@RunWith(classOf[JUnitRunner])
class AppSuite extends AnyFlatSpec with Matchers {
  "A dummy test" should "pass" in {
    assert(true)
  }
}
